### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Cory-Zhao** [yuxiaolejs/cs154-lab3-autograder#1]
When I run this code, I get the error:

./compile.sh: line 5: spim: command not found
cut: text.asm: No such file or directory
sed: 1: "hex.txt": extra characters at the end of h command
Test Failed @ 0 Expected 71 Got undefined
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "undefined".] {
  code: 'ERR_UNHANDLED_REJECTION'}

**Comment by yuxiaolejs** [comment]
Sorry! I forgot to put spim in the dependency list, but you need spim installed for this script to run. Easiest solution will be running it on csil, which has both spim and node installed!

**Comment by yuxiaolejs** [comment]
Really sorry for the inconvenience, everything is fixed in commit ce5b7f3
It can now run without `nodejs` and `spim`, the only thing you need is python and pyrtl!

Since this update resolves the problem you are facing, I am now closing this issue. @Cory-Zhao Thank you for your feedback and contribution! Please let me know if you have any idea that will make this better. 

Happy studying and good luck on your labs!
